# Topic:List, Tuple, Set, Dictionary
# thislist = ["apple", "banana", "cherry"]
# print(thislist)
# # print(thislist[1])
# # print(thislist[-1])
# # print(thislist[2:5])
# print(thislist[:4])
# # print(thislist[2:])   
# print(thislist[-1:-4:-1])    

# list1 = ["apple", "banana", "cherry"]
# list2 = [1, 5, 7, 9, 3]
# list3 = [True, False, False]
# print(list3)
# list4 = ['abc', 34, True, 40, "male"]
# print(list4)

# list1 = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
# print(list1)
# print(list1+["tomato", "grape",140])
# print(list1, ["tomato", "grape",140])
# print(list1*4)
# print(list1[2])
# print(list1[-1:-8:-1])
fruits = ["apple", "banana", "cherry", "orange","cherry","cherry"]
# fruits.append("kiwi")
# print(fruits)
# fruits.insert(1, "lemon")
# print(fruits)
# fruits.remove("banana")
# print(fruits)
# fruits.clear()
# print(fruits)
# fruits.pop()
# print(fruits)
# fruits.count("cherry")
# x=fruits.count("cherry")
# print(x)
# fruits.extend(["grape", "melon", "mango"])
# print(fruits)
# fruits.sort()
# print(fruits)
# fruits.reverse()
# print(fruits)
# fruits.index("cherry")
# x=fruits.index("cherry")
# y=fruits.index("cherry", x+1)
# z=fruits.index("cherry", y+1)
# print(x)
# print(y)
# print(z)
# print(fruits)
fruits.remove("cherry")
fruits.remove("cherry")
fruits.remove("cherry")
print(fruits)